//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCHVRF.VRFTrans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation_TK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation_TK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCHVRF.VRFTrans.Translation_TK", typeof(Translation_TK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Yollu Kaset Yüksek Verimlilik.
        /// </summary>
        internal static string T_1 {
            get {
                return ResourceManager.GetString("T_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticari VRF CO, FSNA6Q.
        /// </summary>
        internal static string T_10 {
            get {
                return ResourceManager.GetString("T_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticari VRF HP, Su Kaynağı.
        /// </summary>
        internal static string T_11 {
            get {
                return ResourceManager.GetString("T_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dört Yönlü Kaset.
        /// </summary>
        internal static string T_12 {
            get {
                return ResourceManager.GetString("T_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orta Statik Kanallı.
        /// </summary>
        internal static string T_13 {
            get {
                return ResourceManager.GetString("T_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Eşanjör (KPI-1).
        /// </summary>
        internal static string T_14 {
            get {
                return ResourceManager.GetString("T_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Eşanjör (KPI-Q2E).
        /// </summary>
        internal static string T_15 {
            get {
                return ResourceManager.GetString("T_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yüksek statik kanallı.
        /// </summary>
        internal static string T_16 {
            get {
                return ResourceManager.GetString("T_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kablosuz Uzaktan Kumanda Anahtarı.
        /// </summary>
        internal static string T_17 {
            get {
                return ResourceManager.GetString("T_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSNA6Q (En iyi deşarj).
        /// </summary>
        internal static string T_18 {
            get {
                return ResourceManager.GetString("T_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Eşanjör (KPI-E4E).
        /// </summary>
        internal static string T_19 {
            get {
                return ResourceManager.GetString("T_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Yönlü Kaset Mini.
        /// </summary>
        internal static string T_2 {
            get {
                return ResourceManager.GetString("T_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Eşanjör (KPI-X4E).
        /// </summary>
        internal static string T_20 {
            get {
                return ResourceManager.GetString("T_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamanlayıcı ile uzaktan kumanda.
        /// </summary>
        internal static string T_3 {
            get {
                return ResourceManager.GetString("T_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticari VRF HP, FSXNPE.
        /// </summary>
        internal static string T_4 {
            get {
                return ResourceManager.GetString("T_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticari VRF HR, FSXNPE.
        /// </summary>
        internal static string T_5 {
            get {
                return ResourceManager.GetString("T_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSXNPE (Üst deşarj).
        /// </summary>
        internal static string T_6 {
            get {
                return ResourceManager.GetString("T_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSXNSE (Üst deşarj).
        /// </summary>
        internal static string T_7 {
            get {
                return ResourceManager.GetString("T_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merkez İstasyonu Mini.
        /// </summary>
        internal static string T_8 {
            get {
                return ResourceManager.GetString("T_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H-Link Rölesi.
        /// </summary>
        internal static string T_9 {
            get {
                return ResourceManager.GetString("T_9", resourceCulture);
            }
        }
    }
}
