//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCHVRF.VRFTrans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCHVRF.VRFTrans.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-2-Way Cassette High Efficiency.
        /// </summary>
        internal static string T_1 {
            get {
                return ResourceManager.GetString("T_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commercial VRF CO, FSNA6Q.
        /// </summary>
        internal static string T_10 {
            get {
                return ResourceManager.GetString("T_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commercial VRF HP, Water Source.
        /// </summary>
        internal static string T_11 {
            get {
                return ResourceManager.GetString("T_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Four Way Cassette.
        /// </summary>
        internal static string T_12 {
            get {
                return ResourceManager.GetString("T_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Medium Static Ducted.
        /// </summary>
        internal static string T_13 {
            get {
                return ResourceManager.GetString("T_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Total Heat Exchanger (KPI-1).
        /// </summary>
        internal static string T_14 {
            get {
                return ResourceManager.GetString("T_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Total Heat Exchanger (KPI-Q2E).
        /// </summary>
        internal static string T_15 {
            get {
                return ResourceManager.GetString("T_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-High Static Ducted.
        /// </summary>
        internal static string T_16 {
            get {
                return ResourceManager.GetString("T_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Wireless Remote Control Switch.
        /// </summary>
        internal static string T_17 {
            get {
                return ResourceManager.GetString("T_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-FSNA6Q (Top discharge).
        /// </summary>
        internal static string T_18 {
            get {
                return ResourceManager.GetString("T_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Total Heat Exchanger (KPI-E4E).
        /// </summary>
        internal static string T_19 {
            get {
                return ResourceManager.GetString("T_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-4-Way Cassette Mini.
        /// </summary>
        internal static string T_2 {
            get {
                return ResourceManager.GetString("T_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Total Heat Exchanger (KPI-X4E).
        /// </summary>
        internal static string T_20 {
            get {
                return ResourceManager.GetString("T_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Compact Ducted (FSN1Q).
        /// </summary>
        internal static string T_21 {
            get {
                return ResourceManager.GetString("T_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-High Static Ducted (FSNQH).
        /// </summary>
        internal static string T_22 {
            get {
                return ResourceManager.GetString("T_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Medium Static Ducted (FSNQH).
        /// </summary>
        internal static string T_23 {
            get {
                return ResourceManager.GetString("T_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Low Static Ducted (FSNQL).
        /// </summary>
        internal static string T_24 {
            get {
                return ResourceManager.GetString("T_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Four Way Cassette (FSN1Q).
        /// </summary>
        internal static string T_25 {
            get {
                return ResourceManager.GetString("T_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Remote control with timer.
        /// </summary>
        internal static string T_3 {
            get {
                return ResourceManager.GetString("T_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commercial VRF HP, FSXNPE.
        /// </summary>
        internal static string T_4 {
            get {
                return ResourceManager.GetString("T_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Commercial VRF HR, FSXNPE.
        /// </summary>
        internal static string T_5 {
            get {
                return ResourceManager.GetString("T_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-FSXNPE (Top discharge).
        /// </summary>
        internal static string T_6 {
            get {
                return ResourceManager.GetString("T_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-FSXNSE (Top discharge).
        /// </summary>
        internal static string T_7 {
            get {
                return ResourceManager.GetString("T_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Central Station Mini.
        /// </summary>
        internal static string T_8 {
            get {
                return ResourceManager.GetString("T_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-H-Link Relay.
        /// </summary>
        internal static string T_9 {
            get {
                return ResourceManager.GetString("T_9", resourceCulture);
            }
        }
    }
}
