//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCHVRF.VRFTrans {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation_ZH {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation_ZH() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCHVRF.VRFTrans.Translation_ZH", typeof(Translation_ZH).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二通道高效室内机.
        /// </summary>
        internal static string T_1 {
            get {
                return ResourceManager.GetString("T_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商用VRF-CO, FSNA6Q.
        /// </summary>
        internal static string T_10 {
            get {
                return ResourceManager.GetString("T_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商用VRF-HP, 水机.
        /// </summary>
        internal static string T_11 {
            get {
                return ResourceManager.GetString("T_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四出口盒型室内机.
        /// </summary>
        internal static string T_12 {
            get {
                return ResourceManager.GetString("T_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中级经典管道型室内机.
        /// </summary>
        internal static string T_13 {
            get {
                return ResourceManager.GetString("T_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全热交换机 (KPI-1).
        /// </summary>
        internal static string T_14 {
            get {
                return ResourceManager.GetString("T_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全热交换机 (KPI-Q2E).
        /// </summary>
        internal static string T_15 {
            get {
                return ResourceManager.GetString("T_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高效静电管道型内机.
        /// </summary>
        internal static string T_16 {
            get {
                return ResourceManager.GetString("T_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无线远程控制器开关.
        /// </summary>
        internal static string T_17 {
            get {
                return ResourceManager.GetString("T_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-FSNA6Q （顶排）.
        /// </summary>
        internal static string T_18 {
            get {
                return ResourceManager.GetString("T_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全热交换机 (KPI-E4E).
        /// </summary>
        internal static string T_19 {
            get {
                return ResourceManager.GetString("T_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四通道迷你室内机.
        /// </summary>
        internal static string T_2 {
            get {
                return ResourceManager.GetString("T_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全热交换机 (KPI-X4E).
        /// </summary>
        internal static string T_20 {
            get {
                return ResourceManager.GetString("T_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时远程遥控器.
        /// </summary>
        internal static string T_3 {
            get {
                return ResourceManager.GetString("T_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商业多连机器-HP, FSXNPE.
        /// </summary>
        internal static string T_4 {
            get {
                return ResourceManager.GetString("T_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商业多连机器-HR, FSXNPE.
        /// </summary>
        internal static string T_5 {
            get {
                return ResourceManager.GetString("T_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-FSXNPE （顶排）.
        /// </summary>
        internal static string T_6 {
            get {
                return ResourceManager.GetString("T_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-FSXNSE （顶排）.
        /// </summary>
        internal static string T_7 {
            get {
                return ResourceManager.GetString("T_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 迷你中心站.
        /// </summary>
        internal static string T_8 {
            get {
                return ResourceManager.GetString("T_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H型线路继电器.
        /// </summary>
        internal static string T_9 {
            get {
                return ResourceManager.GetString("T_9", resourceCulture);
            }
        }
    }
}
